project:
  output-dir: _output
  render:
    - "lecture*/*.qmd"
  resources:
    - "logos/**"
preview:
  port: 4200
  browser: true
  watch-inputs: true
execute:
  python: venv/bin/python
format:
  revealjs:
    theme: [default, custom.scss]
    html-math-method: katex
    chalkboard:
      theme: whiteboard
      buttons: false
    slide-number: true
    footer: "MGFD40"
    logo: "logos/uoft.png"
    transition: slide
    background-transition: fade
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Noto+Serif:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

author:
  - name: Charles Martineau
    affiliation: "UTSC"
    url: "www.charlesmartineau.com"
